baseURL = "https://avinash.com.np"
languageCode = "en-us"
title = "Ramblings and JPT Tech"
theme = "avinash"
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
  post = "/:year/:month/:day/:title"
